### ISSUE TITLE
Redis garbage collection

### ISSUE THREAD

**Issue by will123195** [WW-Digital/mongo-oplog-reader#7]
Currently emitted ops are retained in redis in two separate keys until the TTL expires:

- ``op:${opId}``
- ``emittedEvents:${opId}``

To reduce redis memory usage, there should be a background process that deletes the `op` key if the corresponding `emittedEvents` key exists.

Trying to clean up these keys in real-time is not possible due to race conditions with redundant processes.

**Comment by wwbenomathew** [comment]
When trying to delete is it possible to get a lock on those keys for the first process that hits it?

**Comment by will123195** [comment]
Instead of garbage collecting, we can delete the `op:${opId}` key after attempting to emit the event. I'll add a short delay before deleting to avoid typical race conditions.
